-play mc chill with randomized choices
elenirotsides/Trivia-Bot pull request #59
Opened 2021-04-30 17:55 UTC by sboamah

Still needs the stop functionality in the game itself.

2021-04-30 17:59 UTC, Jhector10 approved these changes

2021-04-30 20:13 UTC, elenirotsides requested changes
![image](https://user-images.githubusercontent.com/43190242/116749442-f42ed880-a9ce-11eb-9957-b591ed9b4a8b.png)

Every question is also showing `NaN` somewhere. I'd say let's investigate this further before we merge this in.

2021-04-30 20:13 UTC, elenirotsides commented on src/bot.js
> +                            +'\n 🇩:' +  parseEntities(choices[3])
```suggestion
                            + '\n 🇦 '+  parseEntities(choices[0])
                            +'\n 🇧 ' +  parseEntities(choices[1])
                            + '\n 🇨 '+  parseEntities(choices[2])
                            +'\n 🇩 ' +  parseEntities(choices[3])
```

2021-04-30 20:13 UTC, elenirotsides commented on src/bot.js
> +                shuffle(choices);
Very cool! I didn't know this was a thing!

2021-05-01 01:36 UTC, elenirotsides approved these changes

2021-05-01 01:36 UTC, merged